/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiUcpRouteImport } from './routes/api/ucp'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as PoliciesRefundRouteImport } from './routes/policies.refund'
import { Route as PoliciesShippingRouteImport } from './routes/policies.shipping'
import { Route as ApiAcpCheckoutSessionsRouteImport } from './routes/api/acp.checkout-sessions'
import { Route as UcpV1ProductsRouteImport } from './routes/ucp/v1/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUcpRoute = ApiUcpRouteImport.update({
  id: '/api/ucp',
  path: '/api/ucp',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundRoute = PoliciesRefundRouteImport.update({
  id: '/policies/refund',
  path: '/policies/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingRoute = PoliciesShippingRouteImport.update({
  id: '/policies/shipping',
  path: '/policies/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcpCheckoutSessionsRoute = ApiAcpCheckoutSessionsRouteImport.update({
  id: '/api/acp/checkout-sessions',
  path: '/api/acp/checkout-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const UcpV1ProductsRoute = UcpV1ProductsRouteImport.update({
  id: '/ucp/v1/products',
  path: '/ucp/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/ucp': typeof ApiUcpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/api/acp/checkout-sessions': typeof ApiAcpCheckoutSessionsRoute
  '/ucp/v1/products': typeof UcpV1ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/ucp': typeof ApiUcpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/api/acp/checkout-sessions': typeof ApiAcpCheckoutSessionsRoute
  '/ucp/v1/products': typeof UcpV1ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/ucp': typeof ApiUcpRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/api/acp/checkout-sessions': typeof ApiAcpCheckoutSessionsRoute
  '/ucp/v1/products': typeof UcpV1ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/mcp'
    | '/api/orders'
    | '/api/ucp'
    | '/checkout/success'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/shipping'
    | '/api/acp/checkout-sessions'
    | '/ucp/v1/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/mcp'
    | '/api/orders'
    | '/api/ucp'
    | '/checkout/success'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/shipping'
    | '/api/acp/checkout-sessions'
    | '/ucp/v1/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/mcp'
    | '/api/orders'
    | '/api/ucp'
    | '/checkout/success'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/shipping'
    | '/api/acp/checkout-sessions'
    | '/ucp/v1/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiUcpRoute: typeof ApiUcpRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesRefundRoute: typeof PoliciesRefundRoute
  PoliciesShippingRoute: typeof PoliciesShippingRoute
  ApiAcpCheckoutSessionsRoute: typeof ApiAcpCheckoutSessionsRoute
  UcpV1ProductsRoute: typeof UcpV1ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ucp': {
      id: '/api/ucp'
      path: '/api/ucp'
      fullPath: '/api/ucp'
      preLoaderRoute: typeof ApiUcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refund': {
      id: '/policies/refund'
      path: '/policies/refund'
      fullPath: '/policies/refund'
      preLoaderRoute: typeof PoliciesRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping': {
      id: '/policies/shipping'
      path: '/policies/shipping'
      fullPath: '/policies/shipping'
      preLoaderRoute: typeof PoliciesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/acp/checkout-sessions': {
      id: '/api/acp/checkout-sessions'
      path: '/api/acp/checkout-sessions'
      fullPath: '/api/acp/checkout-sessions'
      preLoaderRoute: typeof ApiAcpCheckoutSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucp/v1/products': {
      id: '/ucp/v1/products'
      path: '/ucp/v1/products'
      fullPath: '/ucp/v1/products'
      preLoaderRoute: typeof UcpV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiUcpRoute: ApiUcpRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesRefundRoute: PoliciesRefundRoute,
  PoliciesShippingRoute: PoliciesShippingRoute,
  ApiAcpCheckoutSessionsRoute: ApiAcpCheckoutSessionsRoute,
  UcpV1ProductsRoute: UcpV1ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
